# Array Creation

# 1. Using List

In [1]:
    arr=[1, 2, 3, 4, 5]
    for i in arr:
        print(i)

1
2
3
4
5


# 2. Using array functions

In [2]:
import array
  
# initializing array with array values
# initializes array with signed integers
arr = array.array('i', [1, 2, 3]) 
 
# printing original array
print ("The new created array is : ",end="")
for i in range (0,3):
    print (arr[i], end=" ")
 
print ("\r")

The new created array is : 1 2 3 


# 3. Using numpy methods 

In [6]:
# numpy.empty method
 
import numpy as node
 
b = node.empty(2, dtype = int)
print("Matrix b : \n", b)
 
a = node.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = node.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# numpy.zeros method
 
import numpy as node
 
b = node.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = node.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = node.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Reshaping array

In [11]:
# numpy.reshape() method
 
import numpy as node
 
array = node.arange(8)
print("Original array : \n", array)
 
# shape array with 2 rows and 4 columns
array = node.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# shape array with 2 rows and 4 columns
array = node.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# Constructs 3D array
array = node.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# arange([start,] stop[, step,][, dtype]) 

In [13]:
# numpy.arange method
 
import numpy as node
 
print("A\n", node.arange(4).reshape(2, 2), "\n")
 
print("A\n", node.arange(4, 10), "\n")
 
print("A\n", node.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



# numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None) 

In [14]:
# numpy.linspace method
 
import numpy as node
 
# restep set to True
print("B\n", node.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range 
x = node.linspace(0, 2, 10)
print("A\n", node.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


# numpy.ndarray.flatten(order = ‘C’)

In [15]:
# numpy.flatten() method
 
import numpy as node
 
array = node.array([[1, 2], [3, 4]])
 
# using flatten method
array.flatten()
print(array)
 
#using fatten method 
array.flatten('F')
print(array)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


# Methods for array creation in Numpy

empty()	Return a new array of given shape and type, without initializing entries

empty_like()	Return a new array with the same shape and type as a given array

eye()	Return a 2-D array with ones on the diagonal and zeros elsewhere.

identity()	Return the identity array

ones()	Return a new array of given shape and type, filled with ones

ones_like()	Return an array of ones with the same shape and type as a given array

zeros()	Return a new array of given shape and type, filled with zeros

zeros_like()	Return an array of zeros with the same shape and type as a given array

full_like()	Return a full array with the same shape and type as a given array.

array()	Create an array

asarray()	Convert the input to an array

asanyarray()	Convert the input to an ndarray, but pass ndarray subclasses through

ascontiguousarray()	Return a contiguous array in memory (C order)

asmatrix()	Interpret the input as a matrix

copy()	Return an array copy of the given object

frombuffer()	Interpret a buffer as a 1-dimensional array

fromfile()	Construct an array from data in a text or binary file

fromfunction()	Construct an array by executing a function over each coordinate

fromiter()	Create a new 1-dimensional array from an iterable object

fromstring()	A new 1-D array initialized from text data in a string

loadtxt()	Load data from a text file

arange()	Return evenly spaced values within a given interval

linspace()	Return evenly spaced numbers over a specified interval

logspace()	Return numbers spaced evenly on a log scale

geomspace()	Return numbers spaced evenly on a log scale (a geometric progression)

meshgrid()	Return coordinate matrices from coordinate vectors

mgrid()	nd_grid instance which returns a dense multi-dimensional “meshgrid

ogrid()	nd_grid instance which returns an open multi-dimensional “meshgrid

diag()	Extract a diagonal or construct a diagonal array

diagflat()	Create a two-dimensional array with the flattened input as a diagonal

tri()	An array with ones at and below the given diagonal and zeros elsewhere

tril()	Lower triangle of an array

triu()	Upper triangle of an array

vander()	Generate a Vandermonde matrix

mat()	Interpret the input as a matrix

bmat()	Build a matrix object from a string, nested sequence, or array