# Binary Operations

In [3]:
# bitwise_and() function

import numpy as geek
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
  
out_num = geek.bitwise_and(in_num1, in_num2) 
print ("bitwise_and of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_and of 10 and 11 :  10


In [2]:
# bitwise_and() function

import numpy as geek

in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
 
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
  
out_arr = geek.bitwise_and(in_arr1, in_arr2) 
print ("Output array after bitwise_and: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


In [4]:
# bitwise_or() function

import numpy as geek
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
  
out_num = geek.bitwise_or(in_num1, in_num2) 
print ("bitwise_or of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_or of 10 and 11 :  11


In [5]:
# bitwise_or() function

import numpy as geek
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
  
out_num = geek.bitwise_or(in_num1, in_num2) 
print ("bitwise_or of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_or of 10 and 11 :  11


In [6]:
# bitwise_xor() function
 
import numpy as geek
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_xor(in_num1, in_num2) 
print ("bitwise_xor of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_xor of 10 and 11 :  1


In [7]:
# bitwise_xor() function
 
import numpy as geek
 
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_xor(in_arr1, in_arr2) 
print ("Output array after bitwise_xor: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_xor:  [ 1 11 14]


In [8]:
# invert() function
 
import numpy as geek
in_num = 10
print ("Input  number : ", in_num)
   
out_num = geek.invert(in_num) 
print ("inversion of 10 : ", out_num) 

Input  number :  10
inversion of 10 :  -11


In [9]:
# invert() function
 
import numpy as geek
 
in_arr = [2, 0, 25]
print ("Input array : ", in_arr)
   
out_arr = geek.invert(in_arr) 
print ("Output array after inversion: ", out_arr) 


Input array :  [2, 0, 25]
Output array after inversion:  [ -3  -1 -26]


In [10]:
# left_shift() function
 
import numpy as geek
in_num = 5
bit_shift = 2
 
print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift ) 
   
out_num = geek.left_shift(in_num, bit_shift) 
print ("After left shifting 2 bit  : ", out_num) 

Input  number :  5
Number of bit shift :  2
After left shifting 2 bit  :  20


In [11]:
# left_shift() function
 
import numpy as geek
 
in_arr = [2, 8, 15]
bit_shift =[3, 4, 5]
  
print ("Input array : ", in_arr) 
print ("Number of bit shift : ", bit_shift)
   
out_arr = geek.left_shift(in_arr, bit_shift) 
print ("Output array after left shifting: ", out_arr) 

Input array :  [2, 8, 15]
Number of bit shift :  [3, 4, 5]
Output array after left shifting:  [ 16 128 480]


In [12]:
# right_shift() function
 
import numpy as geek
in_num = 20
bit_shift = 2
 
print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift ) 
   
out_num = geek.right_shift(in_num, bit_shift) 
print ("After right shifting 2 bit  : ", out_num) 

Input  number :  20
Number of bit shift :  2
After right shifting 2 bit  :  5


In [13]:
# right_shift() function
 
import numpy as geek
 
in_arr = [24, 48, 16]
bit_shift =[3, 4, 2]
  
print ("Input array : ", in_arr) 
print ("Number of bit shift : ", bit_shift)
   
out_arr = geek.right_shift(in_arr, bit_shift) 
print ("Output array after right shifting: ", out_arr) 

Input array :  [24, 48, 16]
Number of bit shift :  [3, 4, 2]
Output array after right shifting:  [3 3 4]


In [14]:
# binary_repr() function
 
import numpy as geek
in_num = 10
 
print ("Input  number : ", in_num)
 
out_num = geek.binary_repr(in_num) 
print ("binary representation of 10 : ", out_num) 

Input  number :  10
binary representation of 10 :  1010


In [15]:
# binary_repr() function
import numpy as geek
 
in_arr = [5, -8 ]
  
print ("Input array : ", in_arr) 
 
# binary representation of first array  
# element without using width parameter
out_num = geek.binary_repr(in_arr[0])
print("Binary representation of 5")
print ("Without using width parameter : ", out_num) 
 
# binary representation of first array
# element using width parameter
out_num = geek.binary_repr(in_arr[0], width = 5)
print ("Using width parameter: ", out_num) 
 
print("\nBinary representation of -8")
 
# binary representation of 2nd array
# element without using width parameter
out_num = geek.binary_repr(in_arr[1])
print ("Without using width parameter : ", out_num) 
 
# binary representation of 2nd array
# element  using width parameter
out_num = geek.binary_repr(in_arr[1], width = 5)
print ("Using width parameter : ", out_num) 

Input array :  [5, -8]
Binary representation of 5
Without using width parameter :  101
Using width parameter:  00101

Binary representation of -8
Without using width parameter :  -1000
Using width parameter :  11000


In [16]:
# packbits() function
import numpy as np
 
# creating an array using 
# array function
a = np.array([[[1,0,1],
             [0,1,0]],
             [[1,1,0],
             [0,0,1]]])
 
# packing elements of an array
# using packbits() function
b = np.packbits(a, axis=-1)
 
print(b)

[[[160]
  [ 64]]

 [[192]
  [ 32]]]


In [17]:
# unpackbits() function
import numpy as np
 
# creating an array using 
# array function
a = np.array([[2], [7], [23]], dtype=np.uint8)
 
# packing elements of an array
# using packbits() function
b = np.unpackbits(a, axis = 1)
 
print(b)

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 1 1]]
