# Python Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, tools for working with these arrays and also be used as an efficient multi-dimensional container of generic data.

# Creating a Numpy Array

Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining the size of the Array, with the use of various data types such as lists, tuples, etc. 

In [5]:
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with 1 row: \n",arr)

Array with 1 row: 
 [1 2 3]


In [6]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with 2 rows : \n", arr)


Array with 2 rows : 
 [[1 2 3]
 [4 5 6]]


In [7]:
 # Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]


# Accessing the array Index

 Slicing of an array is defining a range in a new array which is used to print a range of elements from the original array. 

In [16]:
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [14]:
 # Printing a range of Array using of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [15]:
# Printing elements at specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


# Basic Array Operations

Operations include some basic Mathematical operation as well as Unary and Binary operations.

In [17]:
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

Adding 1 to every element: [[2 3]
 [4 5]]


In [18]:
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)


Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]


In [19]:
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())


Sum of all array elements:  10


In [20]:
 # Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


# Data Types in Numpy

Every ndarray has an associated data type (dtype) object. This data type object (dtype) provides information about the layout of the array. The values of an ndarray are stored in a buffer which can be thought of as a contiguous block of memory bytes which can be interpreted by the dtype object. 

In [21]:
import numpy as np
 
# Integer datatype guessed by Numpy
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         

Integer Datatype: 
int32


In [30]:
# Float datatype guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  


Float Datatype: 
float64


In [23]:
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


# Math Operations on DataType array

Basic mathematical operations are performed element-wise on the array. 

In [24]:
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]


In [29]:
# Addition of all Array elements using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)


Addition of Array elements: 
19.0


In [26]:
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)


Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [28]:
# Transpose of Array using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)


Transpose of Array: 
[[4. 2.]
 [7. 6.]]


# Methods in Numpy

all()

any()

take()

put()

apply_along_axis()

apply_over_axes()

argmin()

argmax()

nanargmin()

nanargmax()

amax()

amin()

insert()

delete()

append()

around()

flip()

fliplr()

flipud()

triu()

tril()

tri()

empty()

empty_like()

zeros()

zeros_like()

ones()

ones_like()

full_like()

diag()

diagflat()

diag_indices()

asmatrix()

bmat()

eye()

roll()

identity()

arange()

place()

extract()

compress()

rot90()

tile()

reshape()

ravel()

isinf()

isrealobj()

isscalar()

isneginf()

isposinf()

iscomplex()

isnan()

iscomplexobj()

isreal()

isfinite()

isfortran()

exp()

exp2()

fix()

hypot()

absolute()

ceil()

floor()

degrees()

radians()

npv()

fv()

pv()

power()

float_power()

log()

log1()

log2()

log10()

dot()

vdot()

trunc()

divide()

floor_divide()

true_divide()

random.rand()

random.randn()

ndarray.flat()

expm1()

bincount()

rint()

equal()

not_equal()

less()

less_equal()

greater()

greater_equal()

prod()

square()

cbrt()

logical_or()

logical_and()

logical_not()

logical_xor()

array_equal()

array_equiv()

sin()

cos()

tan()

sinh()

cosh()

tanh()

arcsin()

arccos()

arctan()

arctan2()
